
const data = {
    products : [
        {
            _id: '1',
            name: 'Nike slim shirts',
            image: '/images/product-1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Fit shirts',
            image: '/images/product-2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacost Free shirts',
            image: '/images/product-3.jpg',
            price: 20,
            countInStock: 5,
            brand: 'Lacost',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike slim Pant',
            image: '/images/product-4.jpg',
            price: 80,
            countInStock: 50,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma slim pant',
            image: '/images/product-5.jpg',
            price: 110,
            countInStock: 0,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas slim Pant',
            image: '/images/product-6.jpg',
            price: 131,
            countInStock: 3,
            brand: 'Adidas',
            rating: 5.0,
            numReviews: 25,
            description: 'high quality product',
        },
    ],
};

export default data;